imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    translator: { fallbacks: [ "en" ] } 

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email: 
        address: "hello@aquanote.com" 
        sender_name: "AquaNote Postman" 
        
yoh_jasper_report:
    jrs_host:      "%jrs_host%"
    jrs_port:      "%jrs_port%"
    jrs_base:      "%jrs_base%"
    jrs_username:  "%jrs_username%"
    jrs_password:  "%jrs_password%"
    jrs_org_id:    "%jrs_org_id%"
        
easy_admin: 
    list:
        max_results: 15
        actions: ['show']
    site_name: 'Tickets de pesage'
    design:
        form_theme: 'vertical'
        assets:
            css: ['//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css', 'bundles/css/jquery-ui-timepicker-addon.css']
            js: ['https://code.jquery.com/ui/1.12.1/jquery-ui.js', 'bundles/jquery-ui-timepicker-addon.js']
    entities: 
        
        Chauffeurs:
            class: AppBundle\Entity\Chauffeurs
            controller: AppBundle\Controller\ChauffeursController
            # help: 'Global message displayed in all views'
            list:
                sort: ['id', 'ASC']
                fields:
                    - Nom
                    - Prenom
                actions: 
                    - { name: 'edit', icon: 'pencil', label: 'Editer' } 
                    - { name: 'show', icon: 'eye', label: 'Voir' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' } 
            form:
                help: 'Champs marque avec ( * ) sont obligatoires'
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'pencil' }
                    - { property: 'Nom', type_options: { required: true } }    
                    - { property: 'Prenom', type_options: { required: true } }
                    
        Dechets:
            class: AppBundle\Entity\Dechets
            controller: AppBundle\Controller\DechetsController
            list:
                sort: ['id', 'ASC']
                fields:

                    - Code
                    - Categorie
                actions: 
                    - { name: 'edit', icon: 'pencil', label: 'Editer' } 
                    - { name: 'show', icon: 'eye', label: 'Voir' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' } 
            form:
                help: 'Champs marque avec ( * ) sont obligatoires'
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'pencil' }
                    - { property: 'Code', type_options: { required: true } }    
                    - { property: 'Categorie', type_options: { required: true } }        
                    
        Repreneurs:    
            class: AppBundle\Entity\Repreneurs
            controller: AppBundle\Controller\RepreneursController
            list:
                sort: ['id', 'ASC']
                fields:

                    - Nom
                    - Adresse 
                    - Telephone
                    - Fax
                    - { property: 'Email', type: 'email' }
                    - { property: 'SiteWeb', type: 'url' }
                actions: 
                    - { name: 'edit', icon: 'pencil', label: 'Editer' } 
                    - { name: 'show', icon: 'eye', label: 'Voir' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:    
                help: 'Champs marque avec ( * ) sont obligatoires'
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'pencil' }
                    - { property: 'Nom', type_options: { required: true } }    
                    - Adresse
                    - Telephone
                    - Fax
                    - Email
                    - SiteWeb
                    
        Stats:
            class: AppBundle\Entity\Stats
            label: Statistiques
            controller: AppBundle\Controller\StatsController
            templates:
                list: 'easy_admin/Stats/list.html.twig'
            list:
                title: '%%entity_label%%'
                
        Ticket:
            class: AppBundle\Entity\Ticket
            controller: AppBundle\Controller\TicketController
            list:
                sort: ['id', 'ASC']
                fields:

                    - Nticket
                    - DatePesage
                    - Hentree
                    - Hsortie
                    - Tournee
                    - Vehicules
                    - Chauffeurs
                    - Repreneurs
                    - { property: 'Dechets', label: 'Code Dechets' }
                    - Poids
                    - Tarif
                    - Facture
                    - Bonification
                actions: 
                    - { name: 'edit', icon: 'pencil', label: 'Editer' } 
                    - { name: 'show', icon: 'eye', label: 'Voir' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }     
            form:
                help: 'Champs marque avec ( * ) sont obligatoires'
                fields:
                    - { property: 'Nticket', label: 'Numero ticket',  type_options: { required: true } }
                    
                #    - { type: 'group', css_class: 'col-sm-6', label: 'Date et Heure', icon: 'calendar' }
                    - { property: 'DatePesage', type_options: { required: true} }
                    - { property: 'Hentree', label: 'Heure entree' }
                    - { property: 'Hsortie', label: 'Heure sortie' }
                    
                #   - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'pencil' }
                    - { property: 'hiddenVehicules', type: 'choice', type_options: { multiple: true, required: true  } }   
                    - { property: 'hiddenRepreneurs', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true } }                
                    - { property: 'hiddenTournee', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true } }                
                    - { property: 'hiddenChauffeurs', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true } }
                    
                #    - { property: 'Tournee', type: 'hidden' }
                #    - { property: 'Vehicules', type: 'hidden' }
                #    - { property: 'Chauffeurs', type: 'hidden' }
                #    - { property: 'Repreneurs', type: 'hidden' }
                    
                #    - { type: 'group', css_class: 'col-sm-6', label: 'Detail dechets', icon: 'cube'}
                    - { property: 'hiddenDechets', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true } }
                #    - { property: 'Dechets', type: 'hidden' }
                    - { property: 'CategorieDechets', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true } }
                    - { property: 'Poids', type_options: { required: true } }
                    
                #    - { type: 'group', css_class: 'col-sm-6', label: 'Couts', icon: 'credit-card' }
                    - Tarif 
                    - Facture
                    - Bonification
                    # - { type: 'group', css_class: 'new-row ...' }
                    # - { type: 'group', css_class: 'col-sm-6', label: 'Extra' }
                    - { property: 'Remarque', type: 'textarea'  }
                    
        Tournee:       
            class: AppBundle\Entity\Tournee
            controller: AppBundle\Controller\TourneeController
            list:
                sort: ['id', 'ASC']
                fields:

                    - Nom
                    - Frequence
                    - Remarques
                actions: 
                    - { name: 'edit', icon: 'pencil', label: 'Editer' } 
                    - { name: 'show', icon: 'eye', label: 'Voir' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' } 
            form:    
                help: 'Champs marque avec ( * ) sont obligatoires'
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'pencil' }
                    - { property: 'Nom', type_options: { required: true } }    
                    - Frequence
                    - { property: 'Remarques', type: 'textarea'  }
   
        User:
            class: AppBundle\Entity\User
            label: Utilisateurs
            list:
               title: '%%entity_label%%'
               sort: ['id', 'ASC']
               fields:

                    - { property: 'username', label: 'Utilisateur'  }
                    - email
                    - { property: 'enabled', label: 'Active'  }
               actions: 
                    - { name: 'edit', icon: 'pencil', label: 'Editer' } 
                    - { name: 'show', icon: 'eye', label: 'Voir' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            show:
                fields:
                    - username
                    - email
                    - enabled
                    - roles
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
 
        Vehicules:
            class: AppBundle\Entity\Vehicules
            controller: AppBundle\Controller\VehiculesController
            list:
                sort: ['id', 'ASC']
                fields:

                    -  { property: 'Ninterne', label: 'Numero interne'}
                    - Marque
                    - Plaque
                actions: 
                    - { name: 'edit', icon: 'pencil', label: 'Editer' } 
                    - { name: 'show', icon: 'eye', label: 'Voir' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' } 
            form:    
                help: 'Champs marque avec ( * ) sont obligatoires'
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'pencil' }
                    - { property: 'Vehicules', label: 'Numero interne', type_options: { required: true } }    
                    - Marque
                    - Plaque
   
                        